name: "Exemple de workflow"
on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Exécuter l'action Docker
      uses: ./docker-message-action # Utilise l'action locale
      with:
        message: "Salut de l'action Docker"